apiVersion: v1
kind: Pod
metadata:
  name: unauthorized-tester
  namespace: go-security-lab
  labels:
    app: unauthorized-client
spec:
  containers:
    - name: busybox-container
      image: busybox
      command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]